packages:
  - apps/*
  - packages/*
  - tooling/*
  - infra/

catalog:
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  zod: ^3.25.67
  '@tanstack/react-query': ^5.80.7
  '@trpc/client': ^11.4.0
  '@trpc/tanstack-react-query': ^11.4.0
  '@trpc/server': ^11.4.0

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - aws-sdk
  - bufferutil
  - esbuild
  - prisma
  - sharp
